server:
  port: 8003
  servlet:
    context-path: /api
spring:
  profiles:
    active: local
  #项目名称
  application:
    name: zhiqiong
  datasource:
    url: jdbc:mysql://192.168.159.128:3306/zhiqiong?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #redis配置
  redis:
    host: 192.168.159.128
    port: 6379
    password: root
    database: 0
    timeout: 3000
#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: status  #逻辑删除字段
      logic-delete-value: -1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    接口文档配置
knife4j:
  enable: true
  openapi:
    title: 智穹接口文档
    description: 智穹接口文档
    version: 1.0.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.zhiqiong.controller
oapi:
  key: xxxxxxxxx   #换成自己的 oapi key
cos:
  client:
    host: xxxxxxxxx  #域名
    secretId: xxxxxxxxx
    secretKey: xxxxxxxxx
    region: xxxxxxxxx  #区域
    bucket:  #桶名
logging:
  level:
    root: error